### ISSUE TITLE
Empty message if channel is Private and Restrict Saving Content option enabled

### ISSUE THREAD

**Issue by tarkh** [LonamiWebs/Telethon#3264]
As title says, if `Restrict Saving Content` option is enabled on Private channel, then message events from `@client.on(events.NewMessage(channel_id)` contains something like this:
```
NewMessage.Event(original_update=UpdateNewChannelMessage(message=Message(id=12, 
peer_id=PeerChannel(channel_id=123456789), date=datetime.datetime(2022, 1, 3, 9, 59, 10, tzinfo=datetime.timezone.utc), 
message='', out=False, mentioned=False, media_unread=False, silent=False, post=True, from_scheduled=False, legacy=False, 
edit_hide=False, pinned=False, from_id=None, fwd_from=None, via_bot_id=None, reply_to=None, 
media=MessageMediaUnsupported(), reply_markup=None, entities=[], views=1, forwards=0, replies=None, edit_date=None, 
post_author=None, grouped_id=None, restriction_reason=[], ttl_period=None), pts=13, pts_count=1), pattern_match=None, 
message=Message(id=12, peer_id=PeerChannel(channel_id=123456789), date=datetime.datetime(2022, 1, 3, 9, 59, 10, 
tzinfo=datetime.timezone.utc), message='', out=False, mentioned=False, media_unread=False, silent=False, post=True, 
from_scheduled=False, legacy=False, edit_hide=False, pinned=False, from_id=None, fwd_from=None, via_bot_id=None, 
reply_to=None, media=MessageMediaUnsupported(), reply_markup=None, entities=[], views=1, forwards=0, replies=None, 
edit_date=None, post_author=None, grouped_id=None, restriction_reason=[], ttl_period=None))
```
__As we can see, `message` parameter is empty, but on phone client i do see message content.__

So is it a bug in Telethon itself and how it could be fixed? Or this comes from Telegram API and now you can view this type of chats only on official Client? Thanks!

**Comment by LightCannon** [comment]
Same problem occurs with me and I cannot find any workaround it.

**Comment by ArthurTimmermans** [comment]
Same problem ^^

**Comment by Lonami** [comment]
This will be fixed in the next version once the Telegram layer in use is updated.

**Comment by viperadnan-git** [comment]
Hey,
Is this issue resolved in the latest development version ? Because i am still facing it.

**Comment by Lonami** [comment]
This is not yet resolved.

**Comment by thexiox** [comment]
@Lonami Has this problem been resolved? Thanks a lot

**Comment by thexiox** [comment]
@Lonami Has this problem been resolved? Thanks a lot

**Comment by panospet** [comment]
Any news concerning this bug? or at least any workarounds?

**Comment by thexiox** [comment]
> Any news concerning this bug? or at least any workarounds?

La única forma es utilizando la versión de otra persona que los mensajes no llegarían vacíos.

**Comment by vasusen-code** [comment]
Unfortunately i am facing the same problem. Ig it is because telegram doesn't allow it. But @GetAnyMessageBot is able to copy messages from channel with restrictions.

**Comment by tarkh** [comment]
This fork got fix for this issue: https://github.com/kshubham506/Telethon
But anyway waiting for upstream implementation...

**Comment by CaramelHeaven** [comment]
@Lonami The wait is too long. Why can't we just update our core library? This bug has been around since Dec 30th and the main library still can't fix it. Whole month the MAIN library has not normal functionality I assume.

**Comment by Lonami** [comment]
@CaramelHeaven I have a life beyond open source with more pressing matters (after all, maintaining this is a hobby, and I have no obligation to keep working on it), and mental health is important, too. The library has been in desperate need for a major overhaul for over two years now (see #1169), and because of IRL, I haven't been able to dedicate as much time as I would have liked to open source.

However, as of this month, I have been able to keep working on [version 2.0](https://github.com/LonamiWebs/Telethon/tree/v2), which contains over 100 commits, has nearly 200 files changed, and over 10,000 lines changed. This stuff takes time, and dedication. Kindly wait for an update or use a fork in the meantime. You're also welcome to help fix some of the issues to make v2 ready sooner.

**Comment by Lonami** [comment]
Needless to say v2 is still not production ready, but I really had to clean up some of the noise.

**Comment by viper-adnan** [comment]
Still can't read messages, using latest telethon by `pip3 install -U https://github.com/LonamiWebs/Telethon/archive/master.zip`

**Comment by valentino-dicianni** [comment]
I' m using v1.24, but I still have this issue. Message body is empty. Is this the latest version with the fix? @viper-adnan what did you use to make it works?

**Comment by rafaeldcf** [comment]
something is broken in the last update in the master branch and now there is an error with: 
`AttributeError: 'TelegramClient' object has no attribute '_event_builders'`

**Comment by viper-adnan** [comment]
> I' m using v1.24.0, but I still have this issue. Message body is empty. Is this the latest version with the fix? @viper-adnan what did you use to make it works?

It's not working actually because the master branch is not ready for use. It's still in development.

**Comment by yairp03** [comment]
> This issue should now be fixed in the master branch. I have not tried it but it's using the new layer. Needless to say v2 is still not production ready, but I really had to clean up some of the noise. In particular, proxies, entities and sponsored messages still need work.

But the master branch is not working at the moment, so how can I use the new update?

**Comment by carpusmedia** [comment]
Is there anytime timeline for when the new version with a fix will be released?

By the way, huge thanks for this library.

**Comment by nguyenhychan** [comment]
> This fork fixes this issue: https://github.com/kshubham506/Telethon But anyway waiting for upstream implementation...

This works! Thanks so much!

**Comment by carpusmedia** [comment]
@nguyenhychan I wouldn't use that, will likely get you Telegram account banned.

**Comment by yairp03** [comment]
> @nguyenhychan I wouldn't use that, will likely get you Telegram account banned.

Why would you say that?

**Comment by yairp03** [comment]
> I'm just cautious, I read another user got banned. I guess you can use it at your own risk.

You say you can get banned for using this fork, or in general for reading restricted messages?

**Comment by tarkh** [comment]
Get banned for reading restricted messages - that's odd... Basically you can read them, but from official app you can't save or forward. Anyway no one can stop you from reproducing (in any way) information which you have already received. Only if you sign a legal non-disclosure agreement before participate in a private chat/channel.

**Comment by thexiox** [comment]
> Get banned for reading restricted messages - that's odd... Basically you can read them, but from official app you can't save or forward. Anyway no one can stop you from reproducing (in any way) information which you have already received. Only if you sign a legal non-disclosure agreement before participate in a private chat/channel.

Use it but it does not forward, it only extracts the text and the multimedia. Then you put the extracted thing in a variable and send it, then you would not be forwarding.

**Comment by NavruzbekNoraliev** [comment]
this issue is not resolved still, I get  ValueError: The message cannot be empty unless a file is provided
<img width="1318" alt="Screenshot 2022-03-23 at 07 32 05" src="https://user-images.githubusercontent.com/44977644/159615301-c55db85e-e38b-4937-ad92-b4e3dbe75f87.png">

**Comment by gmankab** [comment]
still actual

**Comment by caldetas** [comment]
Same Problem

**Comment by Dammi87** [comment]
Confirmed, still an "issue" on 1.24.0

**Comment by Tyrone1523** [comment]
> 这个分叉解决了这个问题：[https](https://github.com/kshubham506/Telethon) ://github.com/kshubham506/Telethon 但无论如何等待上游实施......

**DO NOT USE THE FORK!!!!**(kshubham506's)
My Account was banned by using it.  (T⌓T) (T⌓T) (T⌓T)
Once you use the fork to get the messages from Private and Restrict group,your account may will got banned !!!!

I am so sad!!!

**Comment by requiemofthesouls** [comment]
same

**Comment by Lonami** [comment]
Please stop notifying everyone by posting "same": I am aware of the issue. You can upvote the original post to show that you have the same issue. It will be fixed in a future version. There is no estimated date for a new release yet. I do not know when it will be.

Regarding forks, I recommend people to choose a trustworthy one, or at the very least, review the changes to make sure it's safe.

**Comment by alex2304** [comment]
> > 这个分叉解决了这个问题：[https](https://github.com/kshubham506/Telethon) ://github.com/kshubham506/Telethon 但无论如何等待上游实施......
> 
> **DO NOT USE THE FORK!!!!**(kshubham506's) My Account was banned by using it. (T⌓T) (T⌓T) (T⌓T) Once you use the fork to get the messages from Private and Restrict group,your account may will got banned !!!!
> 
> I am so sad!!!

Please provide more context on what did you do for getting banned.

Theoretically, Telegram can monitor the content that you received in private chats, and detect that you re-send this content. I know that they for example monitor cases when you send to anyone authorization codes and make them invalid after that.

But in your case, it seems too paranoid, as for me. So please provide the context to verify your statement

**Comment by verifyfx** [comment]
> > > 这个分叉解决了这个问题：[https](https://github.com/kshubham506/Telethon) ://github.com/kshubham506/Telethon 但无论如何等待上游实施......
> > 
> > 
> > **DO NOT USE THE FORK!!!!**(kshubham506's) My Account was banned by using it. (T⌓T) (T⌓T) (T⌓T) Once you use the fork to get the messages from Private and Restrict group,your account may will got banned !!!!
> > I am so sad!!!
> 
> Please provide more context on what did you do for getting banned.
> 
> Theoretically, Telegram can monitor the content that you received in private chats, and detect that you re-send this content. I know that they for example monitor cases when you send to anyone authorization codes and make them invalid after that.
> 
> But in your case, it seems too paranoid, as for me. So please provide the context to verify your statement

I tried the forked library and got banned as well.

steps for reproducing ban:
1. Using main telegram ID, create a private channel with restricted copy enforced
2. Register alternate telegram ID using real phone number
3. Use alternate account to join the created channel in step 1
4. Run a simple script with alternate account that **echo whatever is sent to the channel to stdout**
5. Send multiple text-only messages from the main account to the channel
6. The forked client is able to received ~4 messages before going silent
7. Check the mobile app and the alternate account were banned

**Comment by Lonami** [comment]
If you were banned please see #824. Even if a library or fork is safe (not claiming it is, have not checked), Telegram is who decides the ban. The v1.24 branch in this repository now exists so the fork is not needed if you don't feel confident (`@TelethonUpdates` in Telegram has installation instructions).

**Comment by thexiox** [comment]
> If you were banned please see #824. Even if a library or fork is safe (not claiming it is, have not checked), Telegram is who decides the ban. The v1.24 branch in this repository now exists so the fork is not needed if you don't feel confident (`@TelethonUpdates` in Telegram has installation instructions).

This update allows to obtain the messages of the channels with restricted applied?

**Comment by verifyfx** [comment]
@Lonami Thanks for the #824. Will try the suggestion there.
@thexiox I saw api layer on v1.24 branch got updated to 140. so it should be able to read it now? I will try it when I get back home. https://github.com/LonamiWebs/Telethon/blob/v1.24/telethon_generator/data/api.tl#L1826

**Comment by Lonami** [comment]
> This update allows to obtain the messages of the channels with restricted applied?

Probably. I don't know, I don't think I've encountered such a channel or tried.

**Comment by verifyfx** [comment]
I have tested with a brand new account with the same procedure. it's seems to be able to read contents from `private and restricting saving content enabled` room without getting banned.

Steps I took:
1. uninstall existing telethon `pip uninstall telethon`
2. install telethon from git tag version `pip3 install -U https://github.com/LonamiWebs/Telethon/archive/v1.24.zip`
3. install cryptg (not sure if it's needed but it's nice to have it anyway) `pip install --upgrade cryptg~=0.3`

Thank you @Lonami for dedicating your time to update this amazing library

**Comment by Sh04Un** [comment]
> I have tested with a brand new account with the same procedure. it's seems to be able to read contents from `private and restricting saving content enabled` room without getting banned.
> 
> Steps I took:
> 
> 1. uninstall existing telethon `pip uninstall telethon`
> 2. install telethon from git tag version `pip3 install -U https://github.com/LonamiWebs/Telethon/archive/v1.24.zip`
> 3. install cryptg (not sure if it's needed but it's nice to have it anyway) `pip install --upgrade cryptg~=0.3`
> 
> Thank you @Lonami for dedicating your time to update this amazing library

Bro you truly don't know how much I love you

**Comment by klopodav** [comment]
@verifyfx @Sh04Un Hello there, could you help me with the same issue?
I installed  https://github.com/LonamiWebs/Telethon/archive/v1.24.zip, made a simple client:
```
client = telethon.TelegramClient('session_name', constants.TG_API_ID, constants.TG_API_HASH)
@client.on(telethon.events.NewMessage(chats=(SRC_NAME)))
async def normal_handler(event):
    print(event.message.to_dict())

client.start()
client.run_until_disconnected()
```
Where SRC_NAME is the name of closed channel with enabled option "Restrict saving content".
So, the problem is: it is don't work with channel. It just don't catch messages from it (at the same time it's working with chats with the same option enabled)
I digged  little bit in library and saw, that in classmethod "build" of newmessage file at runtime the library missed first message from channel at all, but I could print others, but still, as I said, my handler couldn't catch them =/

Also, if I send message to/from any other chat I will get a error with the trace (@Lonami maybe it could be helpful for you):

> Task exception was never retrieved
future: <Task finished name='Task-15' coro=<UpdateMethods._dispatch_update() done, defined at .../lib/python3.9/site-packages/telethon/client/updates.py:407> exception=ValueError('Cannot find any entity corresponding to <SRC_NAME>')>
Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/telethon/client/updates.py", line 447, in _dispatch_update
    await builder.resolve(self)
  File ".../lib/python3.9/site-packages/telethon/events/common.py", line 99, in resolve
    await self._resolve(client)
  File ".../lib/python3.9/site-packages/telethon/events/newmessage.py", line 93, in _resolve
    await super()._resolve(client)
  File ".../lib/python3.9/site-packages/telethon/events/common.py", line 103, in _resolve
    self.chats = await _into_id_set(client, self.chats)
  File ".../lib/python3.9/site-packages/telethon/events/common.py", line 33, in _into_id_set
    chat = await client.get_input_entity(chat)
  File ".../lib/python3.9/site-packages/telethon/client/users.py", line 448, in get_input_entity
    await self._get_entity_from_string(peer))
  File ".../lib/python3.9/site-packages/telethon/client/users.py", line 585, in _get_entity_from_string
    raise ValueError(
ValueError: Cannot find any entity corresponding to <SRC_NAME>

So, any thoughts about how can I make it work properly? May be I do something wrong in my code?
I tried to find the diff between 1.24 original version and patched, but it's too many lines) 
Many thanks for any help!

**Comment by klopodav** [comment]
I made it works, but only with channel id, not with channel name

**Comment by Sh04Un** [comment]
> I made it works, but only with channel id, not with channel name
@klopodav 
I was gonna say the same, I pass to it a list of ids, so a variable, the attribute doesn't need parenthesis, so:
@client.on(telethon.events.NewMessage(chats=idList)
sorry for late answer

**Comment by luyifan233** [comment]
> I have tested with a brand new account with the same procedure. it's seems to be able to read contents from `private and restricting saving content enabled` room without getting banned.
> 
> Steps I took:
> 
> 1. uninstall existing telethon `pip uninstall telethon`
> 2. install telethon from git tag version `pip3 install -U https://github.com/LonamiWebs/Telethon/archive/v1.24.zip`
> 3. install cryptg (not sure if it's needed but it's nice to have it anyway) `pip install --upgrade cryptg~=0.3`
> 
> Thank you @Lonami for dedicating your time to update this amazing library

Thanks bro. Acutally, I used v1.24 (a few months ago) when I met the issue #3264. But when I use your method, it  just works. Do you have any clue about it？ thank you for your time : )

**Comment by Sh04Un** [comment]
Pip3 maybe is doing the hidden job? I don't think cryptog makes a
difference

**Comment by verifyfx** [comment]
> > I have tested with a brand new account with the same procedure. it's seems to be able to read contents from `private and restricting saving content enabled` room without getting banned.
> > Steps I took:
> > 
> > 1. uninstall existing telethon `pip uninstall telethon`
> > 2. install telethon from git tag version `pip3 install -U https://github.com/LonamiWebs/Telethon/archive/v1.24.zip`
> > 3. install cryptg (not sure if it's needed but it's nice to have it anyway) `pip install --upgrade cryptg~=0.3`
> > 
> > Thank you @Lonami for dedicating your time to update this amazing library
> 
> Thanks bro. Acutally, I used v1.24 (a few months ago) when I met the issue #3264. But when I use your method, it just works. Do you have any clue about it？ thank you for your time : )

I believe it's because the base api for telegram has been upgraded. In official telethon release package, it has base telegram api version 124 and Lonami upgraded to version 140 in v1.24 tagged release package. the `restrict saving content` feature has been introduced somewhere in the telegram api between version 125-140, so when we run telethon with older api version, it simply doesn't understand message with `restrict saving content` flag enabled. Therefore upgrading to latest api will let the developer map this functionality to the application. as for why using custom telethon package from kshubham506 causes ban? I have no idea but my speculation is it's missing some of the implementation of the new API specification and telegram categorized those pattern to be some kind of an abuser, therefore they banned anyone using that.

**Comment by ruwanaru** [comment]
i have updated to v.24 but my code give empty result > 

**this is my code still didnt work for me can you help me**


`@client.on(telethon.events.NewMessage(chats=-1001768420914))

async def handler(event):
    chat = await event.get_chat()
    msg = event.raw_text
    print(msg)


client.start()
client.run_until_disconnected()`

**Comment by Math-llm-lab** [comment]
> > I have tested with a brand new account with the same procedure. it's seems to be able to read contents from `private and restricting saving content enabled` room without getting banned.
> > Steps I took:
> > 
> > 1. uninstall existing telethon `pip uninstall telethon`
> > 2. install telethon from git tag version `pip3 install -U https://github.com/LonamiWebs/Telethon/archive/v1.24.zip`
> > 3. install cryptg (not sure if it's needed but it's nice to have it anyway) `pip install --upgrade cryptg~=0.3`
> > 
> > Thank you @Lonami for dedicating your time to update this amazing library
> 
> Thanks bro. Acutally, I used v1.24 (a few months ago) when I met the issue #3264. But when I use your method, it just works. Do you have any clue about it？ thank you for your time : )

Several time message read but after restart Empty and I dont understand why? (try uninstall but nothing)
Maybe do you have some advice?
Pls reply who use this method and ok?

**Comment by afterdelight** [comment]
install version 1.25. it worked for me

**Comment by Joost-dm** [comment]
In 1.25 everything is good with messages, but this problem remains with comments. :(

**Comment by Lonami** [comment]
I have no experience with this new feature. However, v1.25 is using a recent Telegram layer, so the problem should not really be occurring unless there is a particular request that must be made for it to work. Do those same comments work in official applications?

**Comment by Joost-dm** [comment]
Yes, it's possible to read comments in official Telegram application, but I have message "Sorry, copying from this group is disabled by admins." trying to copy text from them. In other groups comments collecting is well.

**Comment by Lonami** [comment]
Either Telegram knows about unofficial applications and straight up hides this information or official applications perform some request to access the text. I don't know which of these two options is and have no interest to investigate it myself though.
