### ISSUE TITLE
implement: client.send_reaction("GroupUsername", MessageID, "emojiUnicode")

### ISSUE THREAD

**Issue by ZE1L** [LonamiWebs/Telethon#3842]
add send_reaction as it does not work with telethon so far

https://core.telegram.org/method/messages.sendReaction

**Comment by Lonami** [comment]
The method described works fine in the v1.24 branch using raw API.

**Comment by ZE1L** [comment]
> The method described works fine in the v1.24 branch using raw API.

thanks for the fast reply, can you kindly send me an example of it as ive been stuck on it for days, would be much appreciated

**Comment by ZE1L** [comment]
didnt mean to close

**Comment by ZE1L** [comment]
i cant find it in https://tl.telethon.dev/methods/messages/index.html

"Message Error:  'Message' object has no attribute 'react'"

"'TelegramClient' object has no attribute 'send_reaction'"

**Comment by ZE1L** [comment]
> The method described works fine in the v1.24 branch using raw API.

there are no API on https://tl.telethon.dev/index.html with sendreaction request, i looked everywhere, how do i go about this ?

**Comment by Lonami** [comment]
This issue is a duplicate of #3736 which has the solution.
