### ISSUE TITLE
client connection always fails - AttributeError: type object 'list' has no attribute 'subclass_of_id'

### ISSUE THREAD

**Issue by menasheh** [LonamiWebs/Telethon#166]
I'm trying to get started using Telethon, but there are many obstacles.

Since I've installed via pip, I'm trying to follow the instructions in the readme:
```
>>> from telethon import TelegramClient
>>> api_id = 12345
>>> api_hash = '0123456789abcdef0123456789abcdef'
>>> # 'session_id' can be 'your_name'. It'll be saved as your_name.session
... client = TelegramClient('session_id', api_id, api_hash)
>>> client.connect()
True
>>>
```
This part works fine, with my hash and id, but the next part fails, even with my number switched out for the example:

```
if not client.is_user_authorized():
   client.send_code_request('+34600000000')
   client.sign_in('+34600000000', input('Enter code: '))
   
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Menasheh\Programs\Python\lib\site-packages\telethon\telegram_client.py", line 254, in is_user_authorized
    return self.session and self.get_me() is not None
  File "C:\Users\Menasheh\Programs\Python\lib\site-packages\telethon\telegram_client.py", line 344, in get_me
    return self(GetUsersRequest([InputUserSelf()]))[0]
  File "C:\Users\Menasheh\Programs\Python\lib\site-packages\telethon\tl\functions\users\get_users.py", line 24, in __init__
    self.id = get_input_user(id)
  File "C:\Users\Menasheh\Programs\Python\lib\site-packages\telethon\utils.py", line 107, in get_input_user
    if type(entity).subclass_of_id == 0xe669bf46:  # crc32(b'InputUser')
AttributeError: type object 'list' has no attribute 'subclass_of_id'
```

Windows 10
Python 3.6.1 64 bit
pip 9.0.1
Telethon 0.11.4

Any help would be appreciated.

**Comment by feodoran** [comment]
Some for me, appears to be a problem introduced with https://github.com/LonamiWebs/Telethon/commit/84bb3bb32527eec736f19a5b24a0c5f605a06abc. Previous versions work fine.

**Comment by menasheh** [comment]
confirmed, works in previous version 0.11.2.1

**Comment by Lonami** [comment]
Seems like I forgot to account for those cases were the attribute is a vector, whoops. This will also affect any other `.get_input_*` because they all work the same way, it just hadn't happened yet. Thanks for the report.

**Comment by menasheh** [comment]
Now I'm getting `AttributeError: 'UpdatesTg' object has no attribute 'random_id'` whenever I get an update with 0.11.2.1. Is this related?

**Comment by Lonami** [comment]
> Is this related?

No? What line did you get this on?

**Comment by menasheh** [comment]
Yes, that line. I got the crash on that line any time the client received an update. I'll try it in the new version later and post a new issue if the problem persists.

**Comment by menasheh** [comment]
that message is also gone in the newest version. all good.
